[package]
name = "parallel_map3"
version = "0.1.0"
authors = ["murray501 <m68286832@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4.2"